### ISSUE TITLE
Grundpaket SJAS

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#1]
Ziel: Aufbau Grundpaket/Umgebung für die SJAS

Inhalt:
- [x] Wagon
- [x] Integrationsumgebung
- [x] Gruppenstruktur
- [x] Rollen und Berechtigung
- [x] Anpassungen am Design
- [x] Mehrsprachigkeit
- [ ] Produktionsumgebung
- [x] Travis CI

**Comment by kronn** [comment]
Die Produktionsumgebung wird später eingerichtet, um hier Aufwand und Kosten zu sparen.
