### ISSUE TITLE
Grundpaket: Anpassungen am Design

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_sjas#10]
- [x] Farbschema
- [x] Logo
- [x] weitere SCSS-Anpassungen

See #1

**Comment by hupf** [comment]
Loïc im Mail vom 30.10.:
> Logo. Wobei wir im Verlauf des nächsten Jahres, voraussichtlich, Anpassungen vornehmen werden. Der Jahresbericht (https://sjas.ch/de/ueber-uns/kurzportrait-der-stiftung/) zeigt dir die momentanen Farben (Weiss, Rot, Blau) , welche nächstes Jahr nicht zwingendermassen angepasst werden. Affaire à suivre.

**Comment by hupf** [comment]
Vorlagen:
- https://sjas.ch/media/pdfs/Jahresbericht_DE_web.pdf (Überschriften: Isonorm 3098, Text: News Gothic BQ)
- https://sjas.ch/ (Überschriften: Capita Light, Text: Open Sans)

**Comment by hupf** [comment]
- Bezüglich Schriftarten habe ich mich an die SJAS Website angelehnt, da die Schriften im Jahresbericht kostenpflichtig sind. Die Capita Light habe ich von der Website kopiert und die Open Sans wird über Google Fonts geladen. Ich hoffe das ist OK vom Licensing her.
- Bei den Farben habe ich versucht, neben dem Rot, die Blautöne aus dem Jahresbericht als Akzentfarben reinzunehmen.
- Allgemein habe ich ein paar leichte Anpassungen gemacht um den Look etwas mehr an die Website anzugleichen.

Hier eine Vorschau:
![image](https://user-images.githubusercontent.com/66047/98798606-5a6a7380-240e-11eb-912a-e8772327fc28.png)
