### ISSUE TITLE
Sprachkentnisse auf Person erfassen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#13]
Auf der Person zusätzliche Attribute festlegen:

Sprachkentnisse
DE (Auswahl: Muttersprache, Gute Kenntnisse, Grundkenntnisse, Keine Kenntnisse)
FR (Auswahl: Muttersprache, Gute Kenntnisse, Grundkenntnisse, Keine Kenntnisse)
IT (Auswahl: Muttersprache, Gute Kenntnisse, Grundkenntnisse, Keine Kenntnisse)
ENG (Auswahl: Muttersprache, Gute Kenntnisse, Grundkenntnisse, Keine Kenntnisse)
ES (Auswahl: Muttersprache, Gute Kenntnisse, Grundkenntnisse, Keine Kenntnisse)

Andere Muttersprache: (Freitext)

**Comment by hupf** [comment]
Aktuelle Implementation:
