### ISSUE TITLE
Modul "Lager"

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#14]
Basierend auf "Events" ein eigenes Modul" Lager. Lager und Events werden unterschieden. Es gibt nur eine fachliche Unterscheidung zwischen Event und Lager. Inhaltlich bleibt der Funktionsumfang vorerst gleich. 

Berechtigungen etc. sind alle gleich wie beim Anlass.

- [x] Tab Lager in der Gruppe

- [x] Tab Lager in der linken Navigation (nav-left-list). Logo wie in der PBS Umgebung `fa fa-campground` Gleiche Ansicht wie Events, nur mit Lagern.

- [x] Kurse ausblenden in der Gruppe
- [x] Kurse ausblenden in der linken Navigation

**Comment by hupf** [comment]
Bezüglich Kurse ausblenden habe ich nichts gemacht – die Kurse sind bei gar keinem Gruppentyp erlaubt.
