### ISSUE TITLE
Application Questions als Boolean Checkbox

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#15]
**Ausgangslage:** 
Beim Anmelden an einen Event gibt es oft die Anforderungen gewisse Fragen zu akzeptieren. Beispielsweise die AGB's oder Lagerregeln.

**Soll:**
Zusätzliche Möglichkeit bei Application Questions eine Möglichkeit für eine Checkbox-Frage einfügen.

Mockup beim bearbeiten eines Events:
![Screenshot from 2020-11-06 18-15-27](https://user-images.githubusercontent.com/9592347/98395306-58926000-205c-11eb-8f14-0d6233e4a1d6.png)

Mockup beim erstellen eines Events (die eckigen Klammern sollte eine Checkbox sein):
![Screenshot from 2020-11-06 18-18-31](https://user-images.githubusercontent.com/9592347/98395435-89729500-205c-11eb-8e80-ba9026ee6a71.png)

**Comment by hupf** [comment]
Umsetzung im Core (es wird neu eine einzelne Antwortmöglichkeit erlaubt):
![image](https://user-images.githubusercontent.com/66047/99365996-4b753c80-28b8-11eb-9c1f-7ddef19c1eaa.png)

So sieht das dann aus bei der Anmeldung:
![image](https://user-images.githubusercontent.com/66047/99365885-24b70600-28b8-11eb-9702-30d314938b32.png)
