### ISSUE TITLE
Bestätigungsmail an Teilnehmer

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#22]
**Ziel:** 
Nach erfolgreicher Anmeldung erhält der/die Teilnehmende ein Bestätigungsmail. 

**Umsetzung**

- [x] Mail bei erfolgreicher Anmeldung auf dem Lager. Custom Content: `Lager: E-Mail Anmeldebestätigung`
- [x] Mail wenn Person auf Warteliste landet Custom Content: `Lager: E-Mail Warteliste`
- [x] Mail abhängig von der Sprache der generieren. 

**Inhalt wird über Custiom Content umgesetzt:**
**Mail Struktur:**
Betreff: Ihre Lageranmeldung: `Lagername`
Text: Mehrsprachig gemäss Beispiel unten. Sprache abhängig von gewählter Korrespondenzsprache oder Session Sprache. Was ist einfacher zu implementieren? Übersetzungen werden noch geliefert.
Angaben zum Kind: Attribute gemäss Anmeldung. Muss nicht zwingend eine Tabelle sein. 

**Mailbeispiel:**
Betreff: Ihre Lageranmeldung: Laax GR
Text: 
Vielen Dank für Ihre Anmeldung. Die Anmeldungen werden in der Reihenfolge ihres Eingangs berücksichtigt. Eine Teilnahmebestätigung erhalten Sie kurz nach der Anmeldung, damit Sie auch die Reise in die Schweiz planen können. Alle weiteren Informationen zum Lager erhalten Sie in 3 Monaten. Wir empfehlen Ihnen untenstehenden Text auszudrucken und als Bestätigung Ihrer Anmeldung aufzubewahren.

Angaben Kind |  
-- | --
Vorname | Test
Name | Test
Geburtsdatum | 16.12.1990
Geschlecht | weiblich
Strasse | Test
Postleitzahl | Test
Ort | Test

**Comment by hupf** [comment]
@kronn Gemacht habe ich noch nichts, aber hier meine Erkenntnisse:

Wenn ich das Bedürfnis richtig verstehe, soll für die Lager ein anderes Bestätigungsmail versendet werden als für die Standard-Anlässe (wo der Text _Anlass: E-Mail Anmeldebestätigung_ verwendet wird).

Fragen:
- Es wird auch eine Freigabebestätigung oder eine Abmeldebestätigung versendet. Sind diese beiden nur für Kurse relevant? Oder müssten wir hier auch noch eigene Texte für die Lager erstellen?
- Bei den Anlässen wird im Bestätigungsmail ein PDF angehängt. Soll dies auch bei den Lagern geschehen oder nur bei den Anlässen?

Für die Implementierung würde ich einen neuen `CustomContent` seeden und `Event::ParticipationMailer#confirmation` überschreiben (skizziert):
```
  def confirmation_with_camp(participation)
    @participation = participation

    filename = Export::Pdf::Participation.filename(participation)
    attachments[filename] = Export::Pdf::Participation.render(participation)

    content = if participation.event.is_a?(Event::Camp)
      CONTENT_CAMP_CONFIRMATION
    else
      CONTENT_CONFIRMATION
    end
    compose(person, content)
  end
```

**Comment by kronn** [comment]
Die Freigabebestätigung geht an SJAS-Personen, die eine Anmeldung noch freigeben müssen. Dies kann auf dem Anlass eingestellt werden. Diese Mail geht nicht an Externe, daher erscheint es mir so, als müsste hier nichts angepasst werden.

DIe Abmeldebestätigung kann auch bei allen Anlässen auftreten. Es scheint als wäre dieser Text jedoch generisch genug.

Es gibt noch keine Korrespondenzsprache auf Personen und die Session-Sprache ist nicht trivial herauszufinden. Ist hier versteckt, das jeder eine Korrespondenzsprache hat?

**Comment by kronn** [comment]
NB: aktuell hat keine Rolle bei der SJAS die Berechtigung, Freigaben zu machen. Dies müsste noch definiert werden, wenn das Feature gewünscht ist.

**Comment by kronn** [comment]
Die Mailssprache soll der Sprache der Anmeldeseite entsprechen.

- [ ] Sprache via hidden_field übertragen und in Application/Participation speichern
- [ ] CustomContent/Mailer für Lageranmeldung
- [ ] Freigaben klären -> :question:

**Comment by olibrian** [comment]
Zwei unterschiedliche Mails:
* Anmeldung definitiv zum Event `Anlass: E-Mail Anmeldebestätigung`
* Anmeldung landet auf Warteliste `Anlass: E-Mail Warteliste`

**Comment by olibrian** [comment]
Noch offen:

- [ ] Mail wenn Person auf Warteliste landet
- [ ] Mail abhängig von der Sprache der generieren.
