### ISSUE TITLE
Warteliste auf dem Event/Lager

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#27]
**Ausgangslage:** 
Für ein Lager werden gewisse Anzahl Teilnehmende zugelassen. Wenn dieses Limit erreicht wird, ist zur Zeit keine weitere Anmeldung mehr möglich. 

**Ziel**
Pro Event soll definiert werden können, ob es eine Warteliste gibt oder nicht. Entsprechend ändert sich das Verhalten bei der Anmeldung.

**Lösungsoption 1:**
Auf dem Event soll ausgewählt werden, ob eine Warteliste geführt werden soll.
Anstelle der Rolle "Teilnehmer/-in" wird der Anmeldung die Rolle "Warteliste" vergeben.
Es wird eine Bestätigung zur Aufnahme der Warteliste an den Angemeldeten verschickt.
Die Rolle kann von "Warteliste" auf "Teilnehmer/-in" geändert werden.

**Lösungsoption 2:**
Analog zu Option1, jedoch mit der Warteliste Funktion/Zuteilung von den Kursen.

**Comment by kronn** [comment]
Die Anpassung ist auf der Integrationsumgebung der SJAS zu sehen

**Comment by olibrian** [comment]
Umgesetzt wurde Lösungsvariante 2.

User-Tests:

- [x] Lager mit max Teilnehmerzahl von 2 erstellen. Zwei Personen anmelden, dritte Anmeldung sollte auf der Warteliste landen.
- [x] Weiter Personen zum Lager hinzufügen
- [x] Externe Person anmelden, wenn Lager noch Plätze hat
- [x] Externe Person anmelden, wenn Lager keine Plätze mehr hat

Rückmeldung:

- [ ] Aufruf von Lager (https://sjas.puzzle.ch/de/groups/1/events/28/application_market) schlägt noch mit einem 500er fehl
- [ ] Wenn eine Person direkt als Teilnehmer auf dem Event (https://sjas.puzzle.ch/de/groups/1/events/35/participations?returning=true) hinzugefügt wird, kann die Seite Anmeldungen (application_market) nicht mehr aufgerufen werden. 500er
- [ ] Anmeldungen zählen erst, wenn sie zugeteilt sind. Beispiel: Lager hat 3 Plätze. Zwei Anmeldungen sind zugeteilt. Eine weitere Anmeldung ist vorhanden, aber noch nicht zugeteilt. Weiter Anmeldungen werden aufgenommen und landen nicht auf der Warteliste.
- [ ] Der Text ist etwas kompliziert. Ist `Teilnehmende können auf eine Warteliste geschoben werden, wenn Anmeldungen freigegeben werden. Wenn keine Plätze mehr frei sind, landen neue Anmeldungen automatisch auf der Warteliste.`Wenn keine Plätze mehr frei sind, landen neue Anmeldungen automatisch auf der Warteliste.` Oder was ist die Bedeutung vom ersten Satz?
- [ ] Bei der Anmeldung noch zum Datum die Uhrzeit ergänzen: 
![Screenshot from 2020-12-30 09-19-50](https://user-images.githubusercontent.com/9592347/103338976-71c5f480-4a80-11eb-8fbf-7f8251519df6.png)

- [ ] Text für Warteliste ist etwas unklar ob ich angemeldet bin oder nicht. 
Ist:
```
Teilnahme von Olivier Brian in test wurde erfolgreich erstellt. Bitte überprüfe die Kontaktdaten und passe diese gegebenenfalls an.
Es sind derzeit alle Plätze belegt, die Anmeldung ist auf der Warteliste.
```
Soll: Farbe eher orange und nicht grün
```
Es sind derzeit alle Plätze belegt, die Anmeldung ist auf der Warteliste.
```
