### ISSUE TITLE
Rückmeldungen Lageranmeldung 3

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#35]
Noch zwei Anpassungswünsche:

- [ ] Mehrsprachigkeit von folgenden Felder: Alterskategorie, Bezeichnung, Aufnahmebedingungen auf dem Lager/Events. Analog zu #28 
- [x] Links in diesen Felder sollten auch als Link angezeigt werden. Analog zu #29 
- [x] "Lager" im linken Menü wie auch im Menü pro Gruppe wird nicht übersetzt.

**Comment by kronn** [comment]
Die Übersetzungsdateien musste erstmalig manuell importiert werden, da die Sprachen als neu galten und daher nicht automatisch aktualisiert wurden.
