### ISSUE TITLE
Übersetzungen von Gruppennamen

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_sjas#38]
Gruppennamen sollen übersetzbar sein.

- [ ] Stiftung für junge Auslandschweizer
- [x] Lager -> nicht in alle Sprachen übersetzt
- [x] (Lager soll in "Ferienlager" umbenennt werden)
![image](https://user-images.githubusercontent.com/17568539/105183686-c49a4580-5b2e-11eb-837d-cff87ad36372.png)

**Comment by olibrian** [comment]
Wird im Ticket #https://github.com/hitobito/hitobito/issues/1136 weiterverfolgt.

**Comment by kronn** [comment]
Die Lösung für die SJAS ist, dass man Gruppen, die nur Gruppen, die nur einmal verwendet werden in der Übersetzung so nennt, wie die Gruppenart genannt wird. Dafür sind Übersetzungen vorhanden. Die funktioniert zufällig für die SJAS, ist jedoch keine allgemeine Lösung.
