### ISSUE TITLE
Lageranmeldung, Sprachangenben kein Pflichtfeld?

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_sjas#39]
- [ ] Sprachangaben sollten Pflichtfelder sein
![image](https://user-images.githubusercontent.com/17568539/105184408-9bc68000-5b2f-11eb-8c3f-2cc4f4e9df73.png)

**Comment by olibrian** [comment]
Kann auch auf dem Lager unter Kontaktangaben definiert werden, ob dies Pflicht werden soll oder nicht.

**Comment by olibrian** [comment]
![image](https://user-images.githubusercontent.com/9592347/105327943-cff17d80-5bcf-11eb-8274-8efaf0aeb6e6.png)
