### ISSUE TITLE
Hyperlinks in einem neuen Tab im Browser öffnen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#44]
- [x] Anmeldedaten
- [x] Übersichtsseite Lager

![image](https://user-images.githubusercontent.com/17568539/105875353-fc592f80-5ffd-11eb-95ee-7d91ed8ba85c.png)

Ist: Wenn bei den Lagern ein Link (z.b. bei den Anmeldeangaben) eingefügt wird, wird dieser korrekt als Link angezeigt. Beim öffnen von diesem Link verlässt der User hitobito. 
![image](https://user-images.githubusercontent.com/9592347/105407402-f9d98d00-5c2d-11eb-8b2f-6ff8e837d3c2.png)

Soll: Beim Clicken auf einen Link, soll dieser in einem neuen Tab geöffnet werden.

**Comment by kronn** [comment]
entweder "target"-attribute whitelisten oder alle links mit `target="_blank"` versehen
