### ISSUE TITLE
Ausblenden von öffentlich auf der Telefonnummer

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#45]
Die Checkbox "Öffentlich" ist auf der Anmeldeseite verwirrend. 

![image](https://user-images.githubusercontent.com/9592347/105407729-5e94e780-5c2e-11eb-96d0-543a53873277.png)

Soll: Checkbox, Text und Info ausblenden

Im Wagon sjas ganz entfernen.

**Comment by chrusu** [comment]
duplicate #53
