### ISSUE TITLE
Übersetzung "Durchgeführt von" bei externen Anmeldungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#49]
**Ausgangslage:** 
Bei der Anmeldung als Externe Person auf ein Lager wird der Gruppenname nicht übersetzt
Beispiel: https://sjas.puzzle.ch/en/groups/1/public_events/37
![image](https://user-images.githubusercontent.com/9592347/105491807-36050000-5cb7-11eb-8c1c-b37a17140922.png)

**Soll:**
Als Fix soll hier nicht der Gruppenname, sondern der im Transifex übersetzbarer Name angezeigt werden. Dies als Fix bis die Gruppennamen übersetzbar sind.

**Comment by kronn** [comment]
Ich habe die Übersetzungen direkt eingetragen, damit ist es morgen auf der Integration bereits sichtbar.
