### ISSUE TITLE
Übersetzung Titel bei externer Anmeldung

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_sjas#52]
- [x] FR: Saisir les données de contact de la personne participante
- [x] IT: Registrare i dati di contatto del/la partecipante

![image](https://user-images.githubusercontent.com/17568539/105875870-9de08100-5ffe-11eb-9f8f-efd6f07056cd.png)

**Comment by kronn** [comment]
Auf transifex angepasst, wird beim nächsten  Deployment aufgenommen.

**Comment by chrusu** [comment]
müsen wir schnell anschauen, die Übersetzung konnte ich im transifex nicht finden (kann gut an mir liegen)
und scheint auch nicht deployed zu sein.

**Comment by olibrian** [comment]
Die deutsche Bezeichnung hat geändert, daher waren sie in Transifex nicht mehr übersetzt. Übersetzungen im Transifex (key 218 ) angepasst.
@kronn könntest du bitte nochmals deployen?

**Comment by kronn** [comment]
Neues Deployment ist durch. Die Versionsnummer habe ich nicht angepasst. ich habe verifiziert, dass die Übersetzung angezeigt werden.
