### ISSUE TITLE
Bei Tel. und Email --> Öffentlich immer deaktivieren und nicht anzeigen

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_sjas#53]
- [x] option entfernen
- [x] öffentlich = false

![image](https://user-images.githubusercontent.com/17568539/105879968-15b0aa80-6003-11eb-8a34-4ddd928d240e.png)

**Comment by kronn** [comment]
Erledigt in https://github.com/hitobito/hitobito_sjas/commit/56254c7159633cd45005ebf16e5ff3865e50de1f
