### ISSUE TITLE
Übersetzung nicht komplett

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_sjas#57]
Übersetzung folgt noch.
wo ändern?

- [ ] FR: 

![image](https://user-images.githubusercontent.com/17568539/105882461-f36c5c00-6005-11eb-903a-8eacba63b6a7.png)

**Comment by kronn** [comment]
Die Übersetzungen werden auf transifex gepflegt. Bei Integrationsdeployments werden automatisch die neuesten Übersetzungen geholt, bei Produktionsdeployment ist dieser Schritt grundsätzlich manuell, aber auch in unseren normalen Ablauf eingebaut.
