### ISSUE TITLE
Teilnehmer erscheinen nicht

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_sjas#58]
Es gibt in den Lagern Teilnehmer, sollten die nicht hier erscheinen?

EDIT: Muss mit SJAS zusammen definiert werden

![image](https://user-images.githubusercontent.com/17568539/105882843-6d9ce080-6006-11eb-9506-fd0c518c6812.png)

**Comment by kronn** [comment]
Nein, die Rolle "Teilnehmer" in Teilnehmerpool wird noch nicht automatisch vergeben. Grundsätzlich ist hier ein Automatismus möglich, sollten wir aber genau festhalten, um Überraschungen zu vermeiden. (Verhalten bei Abmeldung? Verhalten, wenn doch keine Teilnahme erfolgt? Verhalten, wenn jemand von der Warteliste nachrückt? Verhalten, wenn jemand auf der Warteliste landet?)

**Comment by olibrian** [comment]
Kann durch #34 gelöst werden
