### ISSUE TITLE
Satz aus Bestätigungsmail löschen

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_sjas#61]
Was ist der Hintergrund dieses Satzes?
Der macht meines Erachtens nur Sinn, wenn die Option einer zwingenden Unterschrift ausgewählt wurde.

Falls dies so ist, bitte entfernen.

![image](https://user-images.githubusercontent.com/17568539/106017309-9d102380-60c0-11eb-8d1c-47651d596d05.png)

**Comment by kronn** [comment]
Anforderung-Hinweis sollte in Conditional
