### ISSUE TITLE
Probleme mit japanischer Telefonnummer

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_sjas#63]
Beim Testen ist der SJAS ein Problem mit einer japanischen Telefonnummer aufgefallen. 

Ich konnte das Problem nicht nachvollziehen, doch möchte ich wissen, was für checks durchgeführt werden bei den Telefonnummern und schauen, ob wir diese ev. entschärfen können.

**Comment by carlobeltrame** [comment]
Wir verwenden das [Phonelib](https://github.com/daddyz/phonelib) gem zur Formatierung und Validierung der Telefonnummern. Als Standard-Land für die Telefonnummern wird die Einstellung von `phone_number.default_country` in config/settings.yml verwendet, was im Core als `CH` eingestellt ist. Aber soweit ich weiss sollte Phonelib trotzdem auch ausländische Nummern akzeptieren.
Um das genauer zu untersuchen müssten wir eine spezifische Nummer haben die fehlschlägt (es können wohl auch einige Nicht-Vorwahl-Ziffern abgeändert werden um Anonymität zu gewährleisten).

**Comment by chrusu** [comment]
verschiedene telnr. varianten, welche im test gebraucht werden können.
+41 79 826 98 31 oder +41 79/826’98’31 oder +41 (0)79-826-98-31

japanische nummer, welche im test der sjas nicht ging, bei mir aber klappt
+81 90 9041 9862

**Comment by kronn** [comment]
Specs mit diesen Daten und ggf. Implementierung anpassen
