### ISSUE TITLE
Grundpaket: Produktionsumgebung

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_sjas#7]
Domain: db.sjas.ch

Vorbereitung der produktiven Umgebung

- [x] kustomize-overlay
- [x] mailkonten
- [x] composition-repo um production-branch erweitern
- [x] jenkins-job
- [x] Credentials im Cryptopus
- [x] DNS
- [x] APPUiO-Projekt anlegen
- [x] initial-setup mit binkli 
- [x] Monitoring (https://docs.puzzle.ch/guides/latest/ruby-rails-user-guide/index.html#_monitoring_einrichten)

See #1

**Comment by olibrian** [comment]
Betreffend DNS bin ich mit sjas dran um die entsprechenden Einträge erstellen zu lassen.

**Comment by kronn** [comment]
Monitoring ist angefragt

**Comment by olibrian** [comment]
DNS ist eingerichtet. 

Kontakt: 
PLUS UND PLUS
Dein Experte für sichere und zuverlässige Business-IT-Lösungen
Felsenaustrasse 17
3004 Bern
031 511 22 33
https://www.plusundplus.ch/
