### ISSUE TITLE
PERSON: J+S Personennnummer

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#71]
Zusätzliches Attribut auf der Person: J+S Personennnummer

Wurde bereits in den Jugendverbänden umgesetzt.

# Fragen

- [x]  Ist es hier vllt sinnvoll, gleich den ganzen youth-wagon einzubinden?
	Siehe https://github.com/hitobito/hitobito_youth/blob/master/README.rdoc 
-> Rücksprache mit Loïc. Wir können direkt den Wagon verwenden.

# Umsetzungsplan

- [x] hitobito_sjas.gemspec erweitern, um `hitobito_youth` zu verwenden
- [x] lib/hitobito_sjas.rb anpassen (require 'hitobito_youth')
- [x] Github-Action anpassen, um hitobito_youth dort mit auszuchecken (siehe PBS o. ä.)
- [x] ggf. eine Spec als Smoke-test hinzufügen, um klarzustellen, dass hitobito_youth ein Teil von SJAS ist
- [x] manuell Interaktion testen:
	- [x] Eingabe und Bearbeiten der J+S Personennnummer
	- [x] Suche nach J+S Personennnummer
	- [x] Anmeldeangabe in Anlässen und Ferienlagern
	- [x] Export einer Person
- [x] Composition-Repo anpassen (devel UND production)
- [x] im Core bin/active_wagon.rb `Setup#dependencies` anpassen
- [x] CHANGELOG-Eintrag

**Comment by TheWalkingLeek** [comment]
Composition Repo nach dem Mergen der PRs anpassen

**Comment by carlobeltrame** [comment]
Es braucht dann auch noch zwei Ergänzung im development-Repo: [[1]](https://github.com/hitobito/development/blob/master/bin/hitobito-clone#L8) [[2]](https://github.com/hitobito/development/blob/535f1c01696bc819e9aef9f59613473d1e32d7d1/docker/active_wagon.rb#L75)
