### ISSUE TITLE
WORDING: Anpassung an unterschliedlichen Labels

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sjas#72]
Anpassen am Wording

Original Anforderung:

	▪ Die Gruppe «Leitende» in «Leiter*innen» geändert werden. -> kann im GUI durch Kunde erfolgen
	▪ Die Rolle «Zivildienstleistender» sollte als Zusatz zur Rolle ausgewählt werden können. Rolle «Zivildienstleistender» in «Zivi» ändern.
	▪ Rolle «Lagerleiter*innen» sollte in «Hauptlagerleiter*innen» umbenannt werden.
	▪ Rolle «Mitleiter*innen» sollte in «Leiter*innen* umbenannt werden.
	▪ Rolle «Köch*in» sollte in «Koch*Köchin» umbenannt werden.
	▪ Gruppennamen «Teilnehmende sollte in Teilnehmer*innen umbenannt werden. -> kann im GUI durch Kunde erfolgen
	▪ Unter der Rubrik Teilnehmende «+Person hinzufügen» müssen die Ferienlager spezifischen Rollen angepasst werden:
		• Hauptleitung -> Hauptleiter*innen
		• Leitung -> Leiter*innen
		• Küche -> Koch*Köchin
		• Teilnehmer/-in -> Teilnehmer*innen

## Anpassen Rollen Leitungspool

**Ist:**

    Lagerleiter*innen: []
    Kursleiter*innen: []
    Mitleiter*innen: []
    Köch*in: []
    Zivildienstleistender: []

**Soll**

    Hauptlagerleiter*in: []
    Kursleiter*in: []
    Leiter*in: []
    Koch*Köchin: []
    Zivildienstleistender: []

## Anpassen Participents bei Events (Anlässe, Kurse, Ferienlager)

**Ist:**

    Hauptleitung
    Leitung
    Küche 
    Teilnehmer/-in

**Soll**

    Hauptleiter*in
    Kursleiter*in 
    Leiter*in
    Koch*Köchin
    Hauptleiter*in Zivi
    Leiter*in Zivi
    Koch*Köchin Zivi
    Teilnehmer*in

Die Übersetzung in en, fr und it erfolgt durch die SJAS.

- Info an Kunde, sobald zur Übersetzung bereit im Transifex
- Sicherstellen, dass die Übersetzungen zurück in die Integration kommen
- Beim produktiven Release Übersetzungen mitnehmen

# Fragen

- [x] Zivi als Rollenzusatz? Möglichkeiten:
	- Jede Rolle einmal normal und einmal als Zivi definieren?

# Tech-Spec

- [x] config/locales/models.sjas.de.yml anpassen
- [x] Event-Roles erweitern
- [x] README.md im Repo anpassen
- [x] CHANGELOG-Eintrag
- [ ] Info durch Entwickler an Kunde, wenn
	- Daten manuell hochgeladen wurden ODER
	- ein Integrationsdeployment erfolgt ist.

**Comment by severinraez** [comment]
Bitte um Review vor Transifex/Deployment
